name: E2E tests run

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, reopened]

env:
  CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}

jobs:
  cypress_run_1:
    runs-on: ubuntu-latest

    steps:
    - name: Get Repo code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install --force

    - name: Run Server & Test
      run: npm run cy:run:server

    - name: Create report
      if: success() || failure()
      run: npm run report:all

    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: mochawesome-report/

  cypress_run_2:
    runs-on: ubuntu-latest
    steps:
    - name: Get Repo code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install --force

    - name: Run Server & Test
      run: npm run cy:run:server

    - name: Create report
      if: success() || failure()
      run: npm run report:all

    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: mochawesome-report/
